locations:
  table1:
  - {x: 2.250, y: 3.118, theta: 0}
  - {x: 2.750, y: 3.118, theta: 0}
  table2:
  - {x: -3.53, y: 3.75, theta: 1.57}
  - {x: -3.53, y: 4.15, theta: 1.57}

objects:
  cube:
    bounds: { xmin: 0.05, xmax: 0.07, ymin: 0.05, ymax: 0.07, zmin: 0.05, zmax: 0.07 }
    location: { xmin: -inf, xmax: inf, ymin: -inf, ymax: inf, zmin: 0.5, zmax: inf }

task:
- action: move
  params:
    location: locations.table1

- action: torso
  params:
    height: 0.4

- action: look
  params:
    pose: {x: 3.7, y: 3.18, z: 0.0, frame: "map"}

- action: perceive
  params:
    object: objects.cube
  vars:
  - cube
  - grasps

- action: pick
  params:
    cube: vars.cube
    grasps: vars.grasps

- action: tuck

- action: torso
  params:
    height: 0.0

- action: move
  params:
    location: table2

- action: torso
  params:
    height: 0.4

- action: place
  params:
    object: vars.cube
    pose: ops.pose_of_object(vars.cube)

- action: tuck

- action: torso
  params:
    height: 0.0
