locations:
  table1:
  - {x: 2.250, y: 3.118, theta: 0, frame: "map"}
  - {x: 2.750, y: 3.118, theta: 0, frame: "map"}
  table2:
  - {x: -3.53, y: 3.75, theta: 1.57, frame: "map"}
  - {x: -3.53, y: 4.15, theta: 1.57, frame: "map"}

objects:
  cube:
    bounds: { xmin: 0.025, xmax: 0.13, ymin: 0.025, ymax: 0.13, zmin: 0.025, zmax: 0.13 }
    location: { xmin: -.inf, xmax: .inf, ymin: -.inf, ymax: .inf, zmin: 0.5, zmax: .inf }

task:
- action: tuck_pose

- action: torso
  params:
    height: 0.0

- action: move
  params:
    location: locations.table1

- action: torso
  params:
    height: 0.4

- action: ready_pose

- action: look
  params:
    pose: {x: 1.5, y: 0.0, z: -1.0, frame: "base_link"}

- action: perceive
  params:
    obj: objects.cube
  var:
  - cube_idx
  - grasps

- action: pick
  params:
    cube_idx: var.cube_idx
    grasps: var.grasps

- action: tuck_pose

- action: torso
  params:
    height: 0.0

- action: move
  params:
    location: locations.table2

- action: torso
  params:
    height: 0.4

- action: drop_pose

# - action: place
#   params:
#     cube: var.cube
#     pose_stamped: ops.pose_of_cube(var.cube)
#     pick_result: var.pick_result

- action: tuck_pose

- action: torso
  params:
    height: 0.0
