tasks:
  # Task used for testing subsets of the main task
  test:
    steps:
    - action: arm
      params:
        poses: joint_poses.tuck

    - action: torso
      params:
        height: 0.0

  # Task for setting up Halloween
  halloween_setup:
    steps:
    - action: arm
      parms:
        poses: joint_poses.ready_for_candy

    - action: gripper
      params:
        command: 'open'

    - action: torso
      parms:
        height: 0.25

    - action: beep
      params:
        beep: cheerful
        async: true

  # The main fetch and deliver task that we want to make robust
  halloween_main:
    steps:
    - action: torso
      params:
        height: 0.25

    - action: arm
      params:
        poses: joint_poses.ready
        look_at_gripper: true

    - action: arm
      params:
        poses: gripper_poses.low
        look_at_gripper: false

    - action: arm
      params:
        poses: joint_poses.ready
        look_at_gripper: true

    - action: arm
      params:
        poses: gripper_poses.med
        look_at_gripper: false

    - action: arm
      params:
        poses: joint_poses.ready
        look_at_gripper: true

    - action: arm
      params:
        poses: gripper_poses.high
        look_at_gripper: false
