tasks:
  # Task used for testing subsets of the main task
  test:
    steps:
    - action: arm
      params:
        poses: joint_poses.tuck

    - action: torso
      params:
        height: 0.0

  # Task for setting up Halloween
  halloween_setup:
    steps:
    - action: arm
      parms:
        poses: joint_poses.ready_for_candy

    - action: gripper
      params:
        command: 'open'

    - action: torso
      parms:
        height: 0.25

    - action: beep
      params:
        beep: cheerful
        async: true

  # The main fetch and deliver task that we want to make robust
  halloween_main:
    steps:
    - action: beep
      params:
        beep: cheerful
        async: true

    - action: torso
      params:
        height: 0.4

    - action: arm
      params:
        poses: joint_poses.tuck
        look_at_gripper: true

    - action: torso
      params:
        height: 0.0

    - action: beep
      params:
        beep: playful
        async: true

    - action: beep
      params:
        beep: surprised
        async: true

    - action: beep
      params:
        beep: unsure
        async: true

    - action: beep
      params:
        beep: happy
        async: true

    - action: beep
      params:
        beep: excited
        async: true

    - action: look
      params:
        pose: {x: 1.5, y: 0.0, z: -1.0, frame: "base_link"}

    - action: beep
      params:
        beep: unsure
        async: true

    - action: place

    - action: beep
      params:
        beep: proud
        async: true

    - action: beep
      params:
        beep: happy
