# The package from where to fetch the actions files
actions: task_executor.actions

tasks:
  #### Choice tests
  choice_test:
    params:
    - param1
    - param2

    var:
    - var1

    steps:
    - choice: choice1
      params:
        condition: "(params.param1 is None and params.param2 is not None)"
        if_true:
          op: assign
          params:
            var_name: var1
            expr: 1
          var:
          - var1
        if_false:
          op: assign
          params:
            var_name: var1
            expr: 2
          var:
          - var1

    - choice: choice2
      params:
        condition: params.param1 == 1
        if_true:
          op: assign
          params:
            var_name: var1
            expr: 3
          var:
          - var1

  #### Loop tests
  loop_test:
    params:
    - num_iterations

    steps:
    - op: assign
      params:
        var_name: cond
        expr: 0
      var:
      - cond

    - loop: loop
      params:
        condition: var.cond < params.num_iterations
        loop_body:
          task: loop_body_test
          params:
            cond: var.cond
          var:
          - cond

  loop_body_test:
    params:
    - cond

    var:
    - cond

    steps:
    - action: trigger
      var:
      - success

    - op: increment
      params:
        var_name: cond
        expr: params.cond + 1
      var:
      - cond
