tasks:
  # Setup for the main task
  setup:
    steps:
    - action: torso
      params:
        height: 0.4

    - action: gripper
      params:
        command: open

    - action: arm
      params:
        poses: joint_poses.tuck
        look_at_gripper: true

    - action: update_beliefs
      params:
        beliefs:
          DOOR_1_OPEN: true
          DOOR_2_OPEN: true
          GRIPPER_HAS_OBJECT: false
          CUBE_AT_PICKUP_1: true

    - action: torso
      params:
        height: 0.0

  # Perception is a task comprising of the find_objects and find_grasps subtasks
  perceive:
    params:
    - obj

    var:
    - cube_idx
    - grasps

    steps:
    - action: look
      params:
        pose: gripper_poses.object_look_location

    - action: find_object
      params:
        obj: params.obj
      var:
      - found_idx
      - found_obj

    - action: find_grasps
      params:
        segmented_obj: var.found_obj
      var:
      - grasps

    - op: assign
      params:
        var_name: cube_idx
        value: var.found_idx
      var:
      - cube_idx

  # Approaching a pickup or dropoff location
  approach:
    params:
      - pre_loc
      - loc

    steps:
    # Move to the location and untuck the arm. Assume the torso is 0 and arm
    # is tucked
    - action: move
      params:
        location: params.pre_loc

    - action: torso
      params:
        height: 0.4

    - action: arm
      params:
        poses: trajectories.tuck_to_stow

    # Clear out the costmap
    - action: look
      params:
        pose: {x: 1.5, y: 0.0, z: -1.0, frame: "base_link"}

    - action: look
      params:
        pose: {x: 50.0, y: 0.0, z: -1.0, frame: "base_link"}

    # Move to the actual location and put the arm in ready
    - action: move
      params:
        location: params.loc

    - action: arm
      params:
        poses: joint_poses.ready

  # Departing a pickup or dropoff location.
  depart:
    params:
      - loc
      - post_loc

    steps:
    # Set the arm to ready, and then to stow. Assume the torso is at max height
    - action: arm
      params:
        poses: joint_poses.ready

    - action: arm
      params:
        poses: joint_poses.stow

    # Clear out the costmap
    - action: look
      params:
        pose: {x: 1.5, y: 0.0, z: -1.0, frame: "base_link"}

    - action: look
      params:
        pose: {x: 50.0, y: 0.0, z: -1.0, frame: "base_link"}

    # Move to the departure staging area and tuck the arm
    - action: move
      params:
        location: params.post_loc

    - action: arm
      params:
        poses: trajectories.stow_to_tuck

    - action: torso
      params:
        height: 0.0

  # Pick up a recognized cube given its grasps
  pick:
    params:
    - cube_idx
    - grasps

    var:
    - grasped

    steps:
    - action: pick
      params:
        cube_idx: params.cube_idx
        grasps: params.grasps

    - action: verify_grasp
      params:
        abort_on_false: true
      var:
      - grasped

    - action: update_beliefs
      params:
        beliefs:
          CUBE_AT_PICKUP_1: false

  # Go through a door
  traverse_doorway:
    params:
    - pre_loc
    - post_loc
    - door_belief

    var:
    - obstacle_in_front

    steps:
    - action: move
      params:
        location: params.pre_loc

    - action: check_obstacle_in_front
      params:
        belief: params.door_belief
        abort_on_true: true
      var:
      - obstacle_in_front

    - action: move
      params:
        location: params.post_loc

  # Place the cube at the desired location
  place:
    steps:
    - action: look
      params:
        pose: gripper_poses.object_look_location

    - action: place

    - action: arm
      params:
        poses: joint_poses.ready

    - action: look
      params:
        pose: gripper_poses.object_look_location

    - action: find_object
      params:
        obj: objects.cube
      var:
      - found_idx
      - found_obj

    - action: update_beliefs
      params:
        beliefs:
          GRIPPER_HAS_OBJECT: false
          CUBE_AT_DROPOFF: true

  # Task used for testing subsets of the main task
  test:
    steps:
    - action: arm
      params:
        poses: joint_poses.tuck

    - action: torso
      params:
        height: 0.0

    - action: move
      params:
        location: locations.pre_table1

  # The main fetch and deliver task that we want to make robust
  main:
    steps:
    - action: beep
      params:
        beep: cheerful
        async: true

    - task: setup

    - action: beep
      params:
        beep: playful
        async: true

    - task: approach
      params:
        pre_loc: locations.pre_table1
        loc: locations.table1

    - action: beep
      params:
        beep: surprised
        async: true

    - action: look
      params:
        pose: gripper_poses.object_look_location

    - action: find_object
      params:
        obj: objects.cube
      var:
      - found_idx
      - found_obj

    - action: beep
      params:
        beep: unsure
        async: true

    - task: pick
      params:
        cube_idx: var.cube_idx
        grasps: var.grasps
      var:
      - grasped

    - action: beep
      params:
        beep: happy
        async: true

    - task: depart
      params:
        loc: locations.table1
        post_loc: locations.post_table1

    - action: beep
      params:
        beep: excited
        async: true

    - task: traverse_doorway
      params:
        pre_loc: locations.door1_out_facing_in
        post_loc: locations.door1_in_facing_in
        door_belief: DOOR_1_OPEN
      var:
      - obstacle_in_front

    - task: approach
      params:
        pre_loc: locations.pre_shelf
        loc: locations.shelf

    - action: beep
      params:
        beep: unsure
        async: true

    - task: place

    - action: beep
      params:
        beep: proud
        async: true

    - task: depart
      params:
        loc: locations.shelf
        post_loc: locations.post_shelf

    - action: beep
      params:
        beep: happy
