# The package from where to fetch the actions files
actions: task_executor.actions

tasks:
  # Conditions test
  conditions_test:
    params:
    - param1
    - param2

    var:
    - var1

    steps:
    - choice: choice1
      params:
        condition: "( params.param1 is None or params.param2 is not None )"
        if_true:
          op: assign
          params:
            var_name: var1
            value: 1
          var:
          - var1

    - choice: choice2
      params:
        condition: params.param1 == 1
        if_true:
          op: assign
          params:
            var_name: var1
            value: 2
          var:
          - var1

  # Loop resumption bug test
  loop_test:
    steps:
    - op: assign
      params:
        var_name: cond
        value: 0
      var:
      - cond

    - loop: loop
      params:
        condition: var.cond <= 5
        loop_body:
          task: loop_body_test
          params:
            cond: var.cond
          var:
          - cond

  loop_body_test:
    params:
    - cond

    var:
    - cond

    steps:
    - op: print_var
      params:
        var_name: cond

    - op: increment
      params:
        var_name: cond
      var:
      - cond

    - op: abort

    - op: print_var
      params:
        var_name: cond

  reposition_recovery_test:
    steps:
    - action: update_beliefs
      params:
        beliefs:
          TASK_AT_GEARBOX_PICK_STATION: true

    - op: abort
