tasks:
  # Task used for testing subsets of the main task
  test:
    steps:
    - action: arm
      params:
        poses: joint_poses.ready

  # Task for setting up Halloween
  setup:
    steps:
    - action: torso
      params:
        height: 0.25

    - task: idle1

    - action: arm
      params:
        poses: joint_poses.pre_pick
        look_at_gripper: true

    - action: gripper
      params:
        command: 'open'

    - action: beep
      params:
        beep: proud

  # The pre-pick task
  pre_pick:
    steps:
    # - action: look
    #   params:
    #     pose: {x: 0.42, y: 0.32, z: 0.61, frame: "base_link"}

    - action: arm
      params:
        poses: joint_poses.pre_pick
        max_velocity_scaling: 0.8

    - action: beep
      params:
        beep: cheerful
        async: true

  # The verification tasks
  move_arm_and_verify:
    params:
    - arm_pose

    var:
    - not_picked

    steps:
    - action: arm
      params:
        poses: params.arm_pose
        max_velocity_scaling: 0.8

    - action: verify_grasp
      var:
      - candy_picked

    - op: negate
      params:
        var_name: candy_picked
        negate_name: not_picked
      var:
      - not_picked

  verify:
    var:
    - not_picked

    steps:
    - action: look
      params:
        pose: { x: 0.3, y: 0.0, z: 0.1, frame: "base_link" }

    - task: move_arm_and_verify
      params:
        arm_pose: joint_poses.candy_verify_1
      var:
      - not_picked

    - choice: candy_verify_2
      params:
        condition: var.not_picked
        if_true:
          task: move_arm_and_verify
          params:
            arm_pose: joint_poses.candy_verify_2
          var:
          - not_picked

  # The stir task
  stir:
    steps:
    - action: detach_candy

    - action: gripper
      params:
        command: open

    - action: arm
      params:
        poses: joint_poses.pre_pick
        max_velocity_scaling: 0.8

    - action: stir

    - action: beep
      params:
        beep: concerned
        async: true

  # The pick loop
  pick_loop:
    var:
    - not_picked

    steps:
    - action: arm
      params:
        poses: joint_poses.pre_pick
        max_velocity_scaling: 0.8

    - action: beep
      params:
        beep: unsure
        async: true

    - action: pick_candy

    - action: beep
      params:
        beep: surprised
        async: true

    - task: verify
      var:
      - not_picked

    - choice: stir_check
      params:
        condition: var.not_picked
        if_true:
          task: stir
        if_false:
          action: beep
          params:
            beep: playful
            async: true

  # The post-pick task
  post_pick:
    var:
    - drop_pose

    steps:
    # This doesn't actually use the value of the choice returned. Also need the
    # detector over here
    - action: joystick_trigger
      var:
      - choice

    # This is a stub
    - op: assign
      params:
        var_name: drop_pose
        value: gripper_poses.default_drop
      var:
      - drop_pose

  # The drop task
  drop:
    params:
    - drop_pose

    steps:
    - action: look
      params:
        pose: params.drop_pose

    - action: arm
      params:
        poses: params.drop_pose

    - action: drop_candy

    - action: beep
      params:
        beep: proud

    - action: arm
      params:
        poses: joint_poses.pre_pick
        look_at_gripper: true

  # The main trick-or-treat task
  main:
    steps:
    - action: beep
      params:
        beep: cheerful
        async: true

    - action: background_task
      params:
        task: dialogue1

    - action: gripper
      params:
        command: open

    - action: detach_candy

    # Move to pre-pick
    - task: pre_pick

    # The pick-verify loop
    - op: assign
      params:
        var_name: not_picked
        value: true
      var:
      - not_picked

    - loop: pick_verify_loop
      params:
        condition: var.not_picked
        loop_body:
          task: pick_loop
          var:
          - not_picked

    # Move to post-pick
    - action: background_task
      params:
        task: dialogue2

    - task: post_pick
      var:
      - drop_pose

    # The drop task
    - task: drop
      params:
        drop_pose: var.drop_pose

  # IDLE
  idle1:
    steps:
    - action: look
      params:
        pose: {x: 5.0, y: 0.0, z: 1.0, frame: "base_link"}

    - action: arm
      params:
        poses: joint_poses.hat_reach_start
        max_velocity_scaling: 0.8

    - action: hat
      params:
        command: hat_reach

    - action: speak
      params:
        text: "Greetings! I do not have <prosody rate=\"x-slow\">a</prosody> monopoly on <prosody rate=\"x-slow\">sweeets</prosody>"
        affect: ""
        async: true

    - action: gripper
      params:
        command: close

    - action: hat
      params:
        command: hat_maneuver

    - action: speak
      params:
        text: "I simply have market share"
        affect: ""
        async: true

    - action: gripper
      params:
        command: open

    - action: hat
      params:
        command: hat_retract

    - action: arm
      params:
        poses: joint_poses.pre_pick
        max_velocity_scaling: 0.8

  # Dialogues
  dialogue1:
    steps:
    - action: look
      params:
        pose: gripper_poses.default_drop

    - action: speak
      params:
        text: "Why, hello there! What is your name?"
        affect: ""

  dialogue2:
    steps:
    - action: look
      params:
        pose: gripper_poses.default_drop

    - action: speak
      params:
        text: "And what are you dressed as today?"
        affect: ""

  joke1:
    steps:
    - action: look
      params:
        pose: gripper_poses.default_drop

    - action: speak
      params:
        text: "What do owls say when they go trick or treating?"
        affect: ""
        async: false

    - action: speak
      params:
        text: "Happy Owl-ween!"
        affect: ""
        async: false

  joke2:
    steps:
    - action: look
      params:
        pose: gripper_poses.default_drop

    - action: speak
      params:
        text: "What do they teach in witching school?"
        affect: ""
        async: false

    - action: speak
      params:
        text: "Spelling."
        affect: ""
        async: false

  joke3:
    steps:
    - action: look
      params:
        pose: gripper_poses.default_drop

    - action: speak
      params:
        text: "What song do vampires hate?"
        affect: ""
        async: false

    - action: speak
      params:
        text: "You Are My Sunshine."
        affect: ""
        async: false

  joke4:
    steps:
    - action: look
      params:
        pose: gripper_poses.default_drop

    - action: speak
      params:
        text: "What type of monster loves dance music?"
        affect: ""
        async: false

    - action: speak
      params:
        text: "The boogieman!"
        affect: ""
        async: false

  joke5:
    steps:
    - action: look
      params:
        pose: gripper_poses.default_drop

    - action: speak
      params:
        text: "Who are cousins of the werewolf?"
        affect: ""
        async: false

    - action: speak
      params:
        text: "What-wolf and When-wolf."
        affect: ""
        async: false

  joke6:
    steps:
    - action: look
      params:
        pose: gripper_poses.default_drop

    - action: speak
      params:
        text: "What do you call a skeleton that sits around all day?"
        affect: ""
        async: false

    - action: speak
      params:
        text: "A lazy bone."
        affect: ""
        async: false

  joke7:
    steps:
    - action: look
      params:
        pose: gripper_poses.default_drop

    - action: speak
      params:
        text: "Which room do ghost houses never have?"
        affect: ""
        async: false

    - action: speak
      params:
        text: "The living room."
        affect: ""
        async: false


