tasks:
  # Task used for testing subsets of the main task
  test:
    steps:
    - action: arm
      params:
        poses: joint_poses.ready

  practice:
    steps:
    - action: beep
      params:
        beep: unsure

  # Task for setting up Halloween
  halloween_setup:
    steps:
    - action: arm
      params:
        poses: joint_poses.ready_for_candy

    - action: gripper
      params:
        command: 'open'

    - action: torso
      params:
        height: 0.25

    - action: beep
      params:
        beep: cheerful
        async: true

  halloween_pick:
    params:
    - num

    var:
    - num
    - not_found

    steps:
    - action: arm
      params:
        poses: joint_poses.ready
        look_at_gripper: true

    - action: arm
      params:
        poses: gripper_poses.low
        look_at_gripper: false

    # - action: arm
    #   params:
    #     poses: joint_poses.ready
    #     look_at_gripper: true

    # - action: arm
    #   params:
    #     poses: gripper_poses.med
    #     look_at_gripper: false

    # - action: arm
    #   params:
    #     poses: joint_poses.ready
    #     look_at_gripper: true

    # - action: arm
    #   params:
    #     poses: gripper_poses.high
    #     look_at_gripper: false

    - op: decrement
      params:
        var_name: num
      var:
      - num

    - op: make_boolean
      params:
        var_name: num
        bool_name: not_found
      var:
      - not_found

  # The main fetch and deliver task that we want to make robust
  halloween_main:
    steps:
    - action: torso
      params:
        height: 0.25

    - op: assign
      params:
        var_name: not_found
        value: true
      var:
      - not_found

    - op: assign
      params:
        var_name: dumb_choice
        value: false
      var:
      - dumb_choice

    - op: assign
      params:
        var_name: num
        value: 1
      var:
      - num

    - loop: pick_verify_loop
      params:
        condition: var.not_found
        loop_body:
          task: halloween_pick
          params:
            num: var.num
          var:
          - num
          - not_found

    - choice: dumb_choice
      params:
        condition: var.dumb_choice
        if_true:
          task: test
        if_false:
          task: practice
