tasks:
  # Task used for testing subsets of the main task
  test:
    steps:
    - action: arm
      params:
        poses: joint_poses.ready

  # Task for setting up Halloween
  setup:
    steps:
    - action: torso
      params:
        height: 0.25

    - action: arm
      params:
        poses: joint_poses.pre_pick
        look_at_gripper: true

    - action: gripper
      params:
        command: 'open'

    - action: beep
      params:
        beep: proud

  # The pre-pick task
  pre_pick:
    steps:
    - action: look
      params:
        pose: {x: 0.05, y: 0.0, z: 0.2, frame: "base_link"}

    - action: arm
      params:
        poses: joint_poses.pre_pick
        look_at_gripper: true
        max_velocity_scaling: 0.8

    - action: beep
      params:
        beep: cheerful
        async: true

  # The verification tasks
  move_arm_and_verify:
    params:
    - arm_pose

    var:
    - not_picked

    steps:
    - action: arm
      params:
        poses: params.arm_pose
        max_velocity_scaling: 0.8

    - action: verify_grasp
      var:
      - candy_picked

    - op: negate
      params:
        var_name: candy_picked
        negate_name: not_picked
      var:
      - not_picked

  verify:
    var:
    - not_picked

    steps:
    - action: look
      params:
        pose: { x: 0.3, y: 0.0, z: 0.1, frame: "base_link" }

    - task: move_arm_and_verify
      params:
        arm_pose: joint_poses.candy_verify_1
      var:
      - not_picked

    - choice: candy_verify_2
      params:
        condition: var.not_picked
        if_true:
          task: move_arm_and_verify
          params:
            arm_pose: joint_poses.candy_verify_2
          var:
          - not_picked

  # The stir task
  stir:
    steps:
    - action: detach_candy

    - action: beep
      params:
        beep: concerned
        async: true

    - action: gripper
      params:
        command: open

    - action: arm
      params:
        poses: joint_poses.pre_pick
        max_velocity_scaling: 0.8

    - action: stir

  # The pick loop
  pick_loop:
    var:
    - not_picked

    steps:
    - action: arm
      params:
        poses: joint_poses.pre_pick
        max_velocity_scaling: 0.8

    - action: beep
      params:
        beep: unsure
        async: true

    - action: pick_candy

    - task: verify
      var:
      - not_picked

    - choice: stir_check
      params:
        condition: var.not_picked
        if_true:
          task: stir
        if_false:
          action: beep
          params:
            beep: playful
            async: true

  # The post-pick task
  post_pick:
    var:
    - drop_pose

    steps:
    - action: arm
      params:
        poses: joint_poses.ready
        max_velocity_scaling: 0.8

    - action: look
      params:
        pose: {x: 50.0, y: 0.0, z: 1.0, frame: "base_link"}

    - action: look
      params:
        pose: {x: 1.5, y: 0.0, z: 1.0, frame: "base_link"}

    - action: look
      params:
        pose: {x: 50.0, y: 0.0, z: 1.0, frame: "base_link"}

    # This doesn't actually use the value of the choice returned. Also need the
    # detector over here
    - action: joystick_trigger
      var:
      - choice

    - action: beep
      params:
        beep: unsure
        async: true

    # This is a stub
    - op: assign
      params:
        var_name: drop_pose
        value: gripper_poses.default_drop
      var:
      - drop_pose

  # The drop task
  drop:
    params:
    - drop_pose

    steps:
    - action: arm
      params:
        poses: params.drop_pose

    - action: drop_candy

    - action: beep
      params:
        beep: proud

    - action: arm
      params:
        poses: joint_poses.ready

  # Dialogues
  dialogue1:
    steps:
    - action: look
      params:
        # needs to modify this pose
        pose: {x: 1.5, y: 0.0, z: -1.0, frame: "base_link"}

    - action: speak
      params:
        text: "hello children"
        affect: "calm"

    - action: beep
      params:
        beep: cheerful
        async: true

  dialogue2:
    steps:
    - action: look
      params:
        # needs to modify this pose
        pose: {x: 1.5, y: 0.0, z: -1.0, frame: "base_link"}

    - action: speak
      params:
        text: "What are you dressed as?"
        affect: "calm"

    - action: beep
      params:
        beep: playful
        async: true

  # The main trick-or-treat task
  main:
    steps:
    - action: beep
      params:
        beep: cheerful
        async: true

    - action: gripper
      params:
        command: open

    - action: detach_candy

    # Move to pre-pick
    - task: pre_pick

    # The pick-verify loop
    - op: assign
      params:
        var_name: not_picked
        value: true
      var:
      - not_picked

    - loop: pick_verify_loop
      params:
        condition: var.not_picked
        loop_body:
          task: pick_loop
          var:
          - not_picked

    # Move to post-pick
    - task: post_pick
      var:
      - drop_pose

    # The drop task
    - task: drop
      params:
        drop_pose: var.drop_pose
