# The different beliefs that can be updated by any node

# Beliefs about the location of the cube
string CUBE_AT_PICKUP_1=cube_at_pickup_1
string CUBE_AT_PICKUP_2=cube_at_pickup_2
string CUBE_AT_DROPOFF=cube_at_dropoff

# Beliefs about the torso
string TORSO_RAISED=torso_raised

# Beliefs about the gripper
string GRIPPER_FULLY_CLOSED=gripper_fully_closed
string GRIPPER_HAS_OBJECT=gripper_has_object

# Beliefs about doors
string DOOR_1_OPEN=door_1_open
string DOOR_2_OPEN=door_2_open

# Beliefs about arm poses
string ARM_AT_TUCK=arm_at_tuck
string ARM_AT_STOW=arm_at_stow
string ARM_AT_READY=arm_at_ready
